/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parqueadero;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Edison Salazar
 */
public class interfasPrincipal extends javax.swing.JFrame {

    DateTimeFormatter fecha = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");

    /**
     * Creates new form interfasPrincipal
     */
    public interfasPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void mensaje(String cad) {
        JOptionPane.showMessageDialog(rootPane, cad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelParqueadero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableTrifas = new javax.swing.JTable();
        jLabelBienvenido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelfecha = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        TxtPlaca = new javax.swing.JTextField();
        jButtonIngresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parqueadero EAS");
        setAlwaysOnTop(true);
        setBackground(null);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(425, 327));
        setMinimumSize(new java.awt.Dimension(425, 327));
        setResizable(false);

        jLabelParqueadero.setFont(new java.awt.Font("Lucida Bright", 1, 28)); // NOI18N
        jLabelParqueadero.setForeground(new java.awt.Color(102, 102, 255));
        jLabelParqueadero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelParqueadero.setText("PARQUEADERO EAS");
        jLabelParqueadero.setMaximumSize(new java.awt.Dimension(68, 22));
        jLabelParqueadero.setOpaque(true);

        jtableTrifas.setBackground(new java.awt.Color(240, 240, 240));
        jtableTrifas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jtableTrifas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtableTrifas.setForeground(new java.awt.Color(51, 51, 51));
        jtableTrifas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Moto",  new Double(3000.0),  new Double(1000.0),  new Double(40000.0)},
                {"", "Carro",  new Double(5000.0),  new Double(1500.0),  new Double(60000.0)}
            },
            new String [] {
                "", "Vehiculo", "Tarifa Dia", "Hora Extra", "Mes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableTrifas.setEnabled(false);
        jtableTrifas.setGridColor(new java.awt.Color(255, 153, 102));
        jtableTrifas.setName("TARIFAS"); // NOI18N
        jtableTrifas.setRowMargin(4);
        jtableTrifas.setRowSelectionAllowed(false);
        jtableTrifas.setShowGrid(true);
        jScrollPane1.setViewportView(jtableTrifas);
        if (jtableTrifas.getColumnModel().getColumnCount() > 0) {
            jtableTrifas.getColumnModel().getColumn(1).setMinWidth(70);
            jtableTrifas.getColumnModel().getColumn(1).setPreferredWidth(70);
            jtableTrifas.getColumnModel().getColumn(1).setMaxWidth(70);
            jtableTrifas.getColumnModel().getColumn(2).setMinWidth(70);
            jtableTrifas.getColumnModel().getColumn(2).setPreferredWidth(70);
            jtableTrifas.getColumnModel().getColumn(2).setMaxWidth(70);
            jtableTrifas.getColumnModel().getColumn(3).setMinWidth(70);
            jtableTrifas.getColumnModel().getColumn(3).setPreferredWidth(70);
            jtableTrifas.getColumnModel().getColumn(3).setMaxWidth(70);
            jtableTrifas.getColumnModel().getColumn(4).setMinWidth(70);
            jtableTrifas.getColumnModel().getColumn(4).setPreferredWidth(70);
            jtableTrifas.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        jLabelBienvenido.setFont(new java.awt.Font("Lucida Bright", 1, 28)); // NOI18N
        jLabelBienvenido.setForeground(new java.awt.Color(102, 102, 255));
        jLabelBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBienvenido.setText("BIENVENIDO");
        jLabelBienvenido.setMaximumSize(new java.awt.Dimension(68, 22));
        jLabelBienvenido.setOpaque(true);

        jLabelfecha.setBackground(new java.awt.Color(153, 255, 153));
        jLabelfecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelfecha.setText("Fecha y Hora: "+fecha.format(LocalDateTime.now()));

        jLabelPlaca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPlaca.setText("Placa:");

        TxtPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPlaca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 102, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 102, 255)));
        TxtPlaca.setRequestFocusEnabled(false);
        TxtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPlacaKeyTyped(evt);
            }
        });

        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Modificar Datos del Cliente");

        btnModificar.setText("Aceptar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(btnModificar)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                            .addComponent(jLabelParqueadero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelBienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelfecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelPlaca)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonIngresar)
                                        .addGap(70, 70, 70)))))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelParqueadero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelfecha)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlaca)
                    .addComponent(TxtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIngresar))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    IngresarDatos IngDat = new IngresarDatos();
    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed

        //Validar que el campo plca este diligenciado
        if (this.TxtPlaca.getText().isEmpty()) {
            mensaje("Ingrese la Placa");
            TxtPlaca.requestFocus();
            return;

        } else {

            //llama al metodo de inicializado en administrar para confirmar si el vehiculo ya esta registrado
            String ban = "registrar";
            IngDat.ValidarPlaca(this.TxtPlaca.getText().toUpperCase(), ban);//uppercase valor en mayusculas                
            this.TxtPlaca.setText("");
            TxtPlaca.requestFocus();
        }

    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void TxtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPlacaKeyTyped
        // TODO add your handling code here:
        if (TxtPlaca.getText().length() >= 6) {// no permite que se ingresen mas de 6 caracteres
            evt.consume();
        }
    }//GEN-LAST:event_TxtPlacaKeyTyped

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        //Validar que el campo plca este diligenciado
        if (this.TxtPlaca.getText().isEmpty()) {
            mensaje("Ingrese la Placa");
            TxtPlaca.requestFocus();
            return;

        } else {

            //llama al metodo de inicializado en administrar para confirmar si el vehiculo ya esta registrado
            String ban = "modificar";
            IngDat.ValidarPlaca(this.TxtPlaca.getText().toUpperCase(), ban);//uppercase valor en mayusculas                
            this.TxtPlaca.setText("");
            TxtPlaca.requestFocus();
        }
    }//GEN-LAST:event_btnModificarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfasPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfasPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtPlaca;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JLabel jLabelParqueadero;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelfecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtableTrifas;
    // End of variables declaration//GEN-END:variables
}
